# https://dev.to/rolanddoda/deploy-to-github-pages-like-a-pro-with-github-actions-4hdg

name: gh-pages

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Clean install dependencies
        run: npm ci
      - name: Deploy
          git checkout --orphan gh-pages
          npm run build
          git config user.name "ramram1048"
          git config user.email "ramram1048@gmail.com"
          git --work-tree dist add --all
          git --work-tree dist commit -m 'Deploy'
          git push origin HEAD:gh-pages --force
          rm -r dist
          git checkout -f master
          git branch -D gh-pages
